---
version: "2"
checks:
  argument-count:
    enabled: false
  file-lines:
    enabled: false
  method-count:
    enabled: false
  return-statements:
    enabled: false
  method-lines:
    config:
      threshold: 100
  method-complexity:
    config:
      threshold: 18
exclude_patterns:
  - "api/*.go"
